### ISSUE TITLE
PCB thickness

### ISSUE THREAD

**Issue by cscott** [zhiayang/mikoto#15]
The README says:
> Since the design contains a controlled-impedance trace (namely the antenna feed), it
> is specific to a given stackup from a given
> manufacturer. The current design files are optimised for JLCPCB's 4-layer 7628 stack
> up.
>
>**read**: if you choose to use a different (1) board thickness, (2) manufacturer, or
> (3) stackup, you ***must*** modify the design

And indeed you specify the manufacturer and stackup -- but I don't think the README ever explicitly specifies the correct board thickness to use?  Reading between the lines (and looking at the KiCad setup) it /seems/ to be the "standard" 1.6mm board thickness, but it would be nice to explicitly say so in the README (if that's right).

Thanks so much for your board!  I'm hacking on it to use for a Ploopy Mini trackball, and it's a great timesaver to have working KiCad files for start with.

**Comment by zhiayang** [comment]
oh, yep -- it's meant to be 1.6mm. I'll add that, thanks!
