### ISSUE TITLE
Changelog for 7.1

### ISSUE THREAD

**Issue by alexmaloteaux** [zhiayang/mikoto#16]
Hi 
Is there any relevant changelog for 7.1 , compared to 6.3 ?
Thanks

**Comment by zhiayang** [comment]
thanks for reminding me, i'll update the doc in the next few days. the main difference is the on-board fuel gauge ic.

**Comment by zhiayang** [comment]
welp, i screwed up rev 7.1, so the changelog isn't important.

**Comment by zhiayang** [comment]
updated
