### ISSUE TITLE
Why there's a voltage regulator in the design?

### ISSUE THREAD

**Issue by marekpiechut** [zhiayang/mikoto#2]
Hi.

Sorry for opening an issue, but found no better place to get in touch with you.

I'm studying the design, and while most of the stuff makes sense for me, I don't get why do you have an external voltage regulator there. It seems that you're powering the battery charger module directly from USB and then connect it directly to VDDH on the MCU. It looks like regulated voltage is only being used to output it on pin 22 of Pro-Micro compatible pins and it's not really needed for the board to work.

Am I right, or am I missing something?
Thanks for help.

**Comment by zhiayang** [comment]
yes, that's right. the LDO is only to power external stuff (eg. LEDs, displays, etc.) on whatever you attach the mikoto to, and not used for anything on-board.

**Comment by marekpiechut** [comment]
That explains it all, thanks.
