### ISSUE TITLE
Hi , has you simulated the antenna signal  in HFSS ?

### ISSUE THREAD

**Issue by xiaoquanaa** [zhiayang/mikoto#3]
Hi , has you simulated the antenna signal  in HFSS ?

**Comment by zhiayang** [comment]
no, i have not.

**Comment by xiaoquanaa** [comment]
so does it works well as a keyboard mcu?

**Comment by xiaoquanaa** [comment]
> no, i have not.

so does it works well as a keyboard mcu?

**Comment by zhiayang** [comment]
the bluetooth radio works well. i have not written the firmware for it yet, but you can get zmk working without too much effort.

**Comment by xiaoquanaa** [comment]
![QQ图片20211007163810](https://user-images.githubusercontent.com/34841255/136350071-fccac7a5-cab7-4ae8-919d-f401aa2bdee8.png)
Hi , i can't understand that why p0.14 and p0.16 i named "reset" , isn't there a default reset pin p0.18?

**Comment by zhiayang** [comment]
if you look at the pcb layout, you will understand why it's necessary. there's no other way to get the reset line out.

**Comment by xiaoquanaa** [comment]
yes , it is true . but i think i can modify de central gnd pad's size of 52840 chip .

**Comment by zhiayang** [comment]
feel free to do that if you want to.
