### ISSUE TITLE
What to choose for layer stackups and other choices for PCB manufacturing?

### ISSUE THREAD

**Issue by Ardakilic** [zhiayang/mikoto#6]
Hello,

I want to try this board, but I'm lost at ordering step. 

While ordering from JLCPCB, what do I have to choose for these layer stackup choices?

![image](https://user-images.githubusercontent.com/2063957/159133778-a7f8814b-8dab-4b88-8978-9d8e8be2dfa7.png)

An example screenshot or list of choices would have been awesome. Even with providing the stackups, I can't enable the SMT assembly, it's telling me to reset the order.

Thanks in advance!

**Comment by zhiayang** [comment]
L1 = F_Cu
L2 = In1_Cu
L3 = In2_Cu
L4 = B_Cu

Stackup = JLC7628

As for assembly, I don't know if they have stock of all the chips (notably the charging IC and MCU itself). Last time I checked you're also limited to green PCBs for 4-layer assembly.

**Comment by Ardakilic** [comment]
Thanks for this. Finally I could pass these parameters. I just wish JLC did not cost $265 for 5 PCB's BOM, and this is even missing nRF52840 itself!

![image](https://user-images.githubusercontent.com/2063957/159177304-d7d446f6-35db-425e-980c-251713de7acb.png)

I'll definitely buy the PCBs and stencil, and source the parts in the future by myself.

Thanks again!

**Comment by zhiayang** [comment]
heck, that is really expensive. it'll be very hard to place/solder the MCU (basically impossible) once the other parts are populated though, so getting it assembled at JLC is usually all-or-nothing.

**Comment by cscott** [comment]
Price seems to be down to $112.50 now, but almost all of that ($77) is due to the extended components fees.  Swapping out "basic" parts might drive this cost down significantly.
