### ISSUE TITLE
why short reset pin with a GPIO pin?

### ISSUE THREAD

**Issue by DoudouMee** [zhiayang/mikoto#7]
- I dont understand why connect reset pin (P0.18/RESET) to P0.14 and P0.16. These 3 GPIO are completely shorted together. 
- If I change the schematic and free them up, can I use they 3 pins as GPIO without short P0.18/RESET to any other pin? 

> ![image](https://user-images.githubusercontent.com/43898894/162587055-9e171e12-baf3-4895-89dd-42be37d9680d.png)

**Comment by zhiayang** [comment]
<img width="224" alt="image" src="https://user-images.githubusercontent.com/500236/162587209-1093d5dc-0923-4356-8a3b-eb556bc04b70.png">

there is no other way to get the reset pin out from under the chip.

**Comment by DoudouMee** [comment]
> <img alt="image" width="224" src="https://user-images.githubusercontent.com/500236/162587209-1093d5dc-0923-4356-8a3b-eb556bc04b70.png">
> 
> there is no other way to get the reset pin out from under the chip.

- soga!
- So, in fact I dont need a high voltage on  P0.18/RESET when this Soc starting up?

**Comment by zhiayang** [comment]
no, the reset pin has an internal pullup on nRF chips.

**Comment by DoudouMee** [comment]
I see, thanks a lot.
